### PR TITLE
feat(property-definition-node): support new PropertyDefinition node

### PR DESCRIPTION
**Pull request by maclockard**

### CODE REVIEW

**Comment by blutorange** [comment]
Would be great if this could get merged. Without this it effectively prevents this plugin from being used with ESLint 8, since this new node type was introduced in typescript-eslint@5.0.0 (https://github.com/typescript-eslint/typescript-eslint/releases/tag/v5.0.0), which is also the first version that supports ESLint 8.

**Comment by maclockard** [comment]
@blutorange if you want to live dangerously, you can use the branch from this PR to unblock yourself by adding something like this to your `package.json`:
```json
"eslint-plugin-tree-shaking": "maclockard/eslint-plugin-tree-shaking#maclockard/support-property-definition-node"
```

**Comment by blutorange** [comment]
Thanks, that was pretty quick. As feedback: I just tried it with a project that uses ESLint 8, the tree shaking plugin seems to be working without issues now.

**Pull request merged**
